version: "3.2"

services:
  taller-auth:
    image: taller-auth-service
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 7082:8000
    env_file:
      - .env
    networks:
      - taller

networks:
  taller:
    external: true
